import json

def create_notebook(filename, cells_data):
    cells = []
    for ctype, content in cells_data:
        if ctype == 'markdown':
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [line + "\n" for line in content.split('\n')]
            })
        else:
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [line + "\n" for line in content.split('\n')]
            })
            
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)

nb1_cells = [
    ("markdown", "# Tarea 4 - Punto 2: Robot Repartidor de Galletas\nEn este notebook implementamos un algoritmo de Programación Genética para entrenar a un robot a repartir galletas a ingenieros en una sala cuadrada."),
    ("code", "!pip install deap matplotlib numpy"),
    ("markdown", "## 1. Definición del Entorno\nSimularemos una sala de 10x10 donde el robot inicia en la posición (0,0) y los ingenieros están repartidos aleatoriamente."),
    ("code", "import random\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom deap import base, creator, tools, gp\nimport operator\n\n# Tamaño de la sala e ingenieros\nGRID_SIZE = 10\nNUM_ENGINEERS = 15\n\nclass Simulator:\n    def __init__(self, seed=None):\n        if seed is not None:\n            random.seed(seed)\n        self.grid = np.zeros((GRID_SIZE, GRID_SIZE))\n        # Colocar ingenieros (representados por 1)\n        engineers_placed = 0\n        while engineers_placed < NUM_ENGINEERS:\n            x, y = random.randint(0, GRID_SIZE-1), random.randint(0, GRID_SIZE-1)\n            if self.grid[y, x] == 0:\n                self.grid[y, x] = 1\n                engineers_placed += 1\n        self.robot_pos = [0, 0]\n        self.robot_dir = 0 # 0: derecha, 1: abajo, 2: izquierda, 3: arriba\n        self.cookies_delivered = 0\n        self.steps = 0\n        self.max_steps = 200\n        self.path = [(0,0)]\n\n    def get_forward_pos(self):\n        x, y = self.robot_pos\n        if self.robot_dir == 0: x += 1\n        elif self.robot_dir == 1: y += 1\n        elif self.robot_dir == 2: x -= 1\n        elif self.robot_dir == 3: y -= 1\n        return [x, y]\n\n    def is_engineer_ahead(self):\n        fx, fy = self.get_forward_pos()\n        if 0 <= fx < GRID_SIZE and 0 <= fy < GRID_SIZE:\n            return self.grid[fy, fx] == 1\n        return False\n\n    def move_forward(self):\n        if self.steps >= self.max_steps: return\n        self.steps += 1\n        fx, fy = self.get_forward_pos()\n        if 0 <= fx < GRID_SIZE and 0 <= fy < GRID_SIZE:\n            self.robot_pos = [fx, fy]\n            self.path.append(tuple(self.robot_pos))\n            if self.grid[fy, fx] == 1:\n                self.grid[fy, fx] = 0 # Entregó galleta\n                self.cookies_delivered += 1\n\n    def turn_left(self):\n        if self.steps >= self.max_steps: return\n        self.steps += 1\n        self.robot_dir = (self.robot_dir - 1) % 4\n\n    def turn_right(self):\n        if self.steps >= self.max_steps: return\n        self.steps += 1\n        self.robot_dir = (self.robot_dir + 1) % 4"),
    ("markdown", "## 2. Definición de la Programación Genética (DEAP)\nDefinimos el conjunto de terminales (acciones) y funciones (control de flujo)."),
    ("code", "# Funciones de envoltorio (wrapper) para el control de flujo en el árbol sintáctico\nimport functools\ndef progn(*args):\n    for arg in args:\n        arg() # Ejecuta las funciones que recibe\n\ndef prog2(out1, out2):\n    return functools.partial(progn, out1, out2)\n\ndef prog3(out1, out2, out3):\n    return functools.partial(progn, out1, out2, out3)\n\n# La implementación de PG requiere que las primitivas manipulen el simulador.\n# Para evitar problemas de ámbito de DEAP, usaremos funciones con estado global.\nimport copy\n\ncurrent_sim = None\n\ndef m_move():\n    global current_sim\n    if current_sim: current_sim.move_forward()\n\ndef m_left():\n    global current_sim\n    if current_sim: current_sim.turn_left()\n\ndef m_right():\n    global current_sim\n    if current_sim: current_sim.turn_right()\n\ndef m_sense():\n    global current_sim\n    return current_sim.is_engineer_ahead() if current_sim else False\n\ndef m_if(out1, out2):\n    def wrapper():\n        if m_sense(): out1()\n        else: out2()\n    return wrapper\n\n# DEAP setup\npset = gp.PrimitiveSet(\"MAIN\", 0)\npset.addPrimitive(prog2, 2, name=\"prog2\")\npset.addPrimitive(prog3, 3, name=\"prog3\")\npset.addPrimitive(m_if, 2, name=\"if_engineer_ahead\")\npset.addTerminal(m_move, name=\"Avanzar\")\npset.addTerminal(m_left, name=\"GirarIzq\")\npset.addTerminal(m_right, name=\"GirarDer\")\n\ncreator.create(\"FitnessMax\", base.Fitness, weights=(1.0,))\ncreator.create(\"Individual\", gp.PrimitiveTree, fitness=creator.FitnessMax)\n\ntoolbox = base.Toolbox()\ntoolbox.register(\"expr_init\", gp.genHalfAndHalf, pset=pset, min_=1, max_=2)\ntoolbox.register(\"individual\", tools.initIterate, creator.Individual, toolbox.expr_init)\ntoolbox.register(\"population\", tools.initRepeat, list, toolbox.individual)"),
    ("markdown", "Ahora definimos la evaluación global del robot."),
    ("code", "def evalRobotGlobal(individual):\n    global current_sim\n    routine = gp.compile(individual, pset)\n    current_sim = Simulator()\n    \n    while current_sim.steps < current_sim.max_steps and current_sim.cookies_delivered < NUM_ENGINEERS:\n        routine()\n        \n    return current_sim.cookies_delivered,\n\ntoolbox.register(\"evaluate\", evalRobotGlobal)\ntoolbox.register(\"select\", tools.selTournament, tournsize=3)\ntoolbox.register(\"mate\", gp.cxOnePoint)\ntoolbox.register(\"expr_mut\", gp.genFull, min_=0, max_=2)\ntoolbox.register(\"mutate\", gp.mutUniform, expr=toolbox.expr_mut, pset=pset)"),
    ("markdown", "## 3. Entrenamiento\nEjecutamos el algoritmo genético para evolucionar el mejor comportamiento del robot."),
    ("code", "from deap import algorithms\n\npop = toolbox.population(n=100)\nhof = tools.HallOfFame(1)\nstats = tools.Statistics(lambda ind: ind.fitness.values)\nstats.register(\"avg\", np.mean)\nstats.register(\"std\", np.std)\nstats.register(\"min\", np.min)\nstats.register(\"max\", np.max)\n\nprint(\"Iniciando evolución...\")\npop, logbook = algorithms.eaSimple(pop, toolbox, 0.5, 0.1, 40, stats=stats, halloffame=hof, verbose=True)\nprint(\"¡Evolución terminada!\")"),
    ("markdown", "## 4. Visualización del mejor individuo"),
    ("code", "import time\nfrom IPython.display import clear_output\n\nbest_ind = hof[0]\nprint(\"Mejor programa genético:\\n\", best_ind)\n\n# Simulamos con una semilla fija para poder ver exactamente qué hizo el robot\nseed_test = 42\ncurrent_sim = Simulator(seed=seed_test)\noriginal_grid = current_sim.grid.copy()\n\nroutine = gp.compile(best_ind, pset)\nwhile current_sim.steps < current_sim.max_steps and current_sim.cookies_delivered < NUM_ENGINEERS:\n    routine()\n\nprint(f\"Galletas entregadas: {current_sim.cookies_delivered}/{NUM_ENGINEERS} en {current_sim.steps} pasos\")\nprint(\"Preparando visualización en vivo...\")\ntime.sleep(2)\n\n# Reproducir el camino en vivo\npath = current_sim.path\nlive_grid = original_grid.copy()\n\nfor i in range(len(path)):\n    clear_output(wait=True)\n    fig, ax = plt.subplots(figsize=(6,6))\n    \n    # Dibujar ingenieros restantes\n    for y in range(GRID_SIZE):\n        for x in range(GRID_SIZE):\n            if live_grid[y, x] == 1:\n                ax.plot(x, y, marker='*', color='orange', markersize=15)\n                \n    rx, ry = path[i]\n    if live_grid[ry, rx] == 1:\n        live_grid[ry, rx] = 0 # Entregó galleta en la animación\n        \n    # Dibujar camino recorrido\n    if i > 0:\n        p_arr = np.array(path[:i+1])\n        ax.plot(p_arr[:,0], p_arr[:,1], color='blue', alpha=0.3, linewidth=2)\n        \n    # Dibujar robot\n    ax.plot(rx, ry, marker='s', color='red', markersize=12)\n    \n    ax.set_xlim(-0.5, GRID_SIZE-0.5)\n    ax.set_ylim(-0.5, GRID_SIZE-0.5)\n    ax.invert_yaxis()\n    ax.set_title(f\"Paso {i}/{len(path)-1} | Galletas entregadas: {NUM_ENGINEERS - int(np.sum(live_grid))}/{NUM_ENGINEERS}\")\n    ax.grid(True)\n    \n    plt.show()\n    time.sleep(0.1)\n\nprint(\"¡Recorrido finalizado!\")")
]

nb2_cells = [
    ("markdown", "# Tarea 4 - Punto 4: Problema Inventado (Consumo Energético de Mini-Robot)\nEn este notebook aplicaremos Programación Genética para realizar **Regresión Simbólica**. El objetivo es encontrar la fórmula matemática que modela el consumo energético de un mini-robot basándonos en su velocidad, peso y la inclinación del terreno."),
    ("code", "!pip install deap matplotlib numpy"),
    ("markdown", "## 1. Creación del Dataset Simulado\nVamos a generar datos basados en una fórmula real (que el algoritmo no conoce): `Energia = 2 * Velocidad^2 + 0.5 * Peso * Inclinacion + 10`"),
    ("code", "import random\nimport math\nimport operator\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom deap import base, creator, tools, gp\n\n# Generar datos\nrandom.seed(42)\nNUM_SAMPLES = 100\n\ndef real_energy(v, p, i):\n    return 2 * (v**2) + 0.5 * p * i + 10\n\ndataset = []\nfor _ in range(NUM_SAMPLES):\n    v = random.uniform(0, 5) # Velocidad\n    p = random.uniform(1, 10) # Peso\n    i = random.uniform(-10, 10) # Inclinación\n    e = real_energy(v, p, i) + random.gauss(0, 2) # Añadimos ruido para hacerlo más realista\n    dataset.append((v, p, i, e))\n    \nprint(\"Dataset generado con 100 muestras.\")\nprint(\"Ejemplo (v, p, i, e):\", dataset[0])"),
    ("markdown", "## 2. Configuración de Programación Genética\nDefinimos los conjuntos de funciones (operaciones matemáticas) y terminales (las variables v, p, i y constantes)."),
    ("code", "def protectedDiv(left, right):\n    try: return left / right\n    except ZeroDivisionError: return 1.0\n\npset = gp.PrimitiveSet(\"MAIN\", 3) # 3 variables de entrada: ARG0(v), ARG1(p), ARG2(i)\npset.renameArguments(ARG0=\"v\")\npset.renameArguments(ARG1=\"p\")\npset.renameArguments(ARG2=\"i\")\n\npset.addPrimitive(operator.add, 2)\npset.addPrimitive(operator.sub, 2)\npset.addPrimitive(operator.mul, 2)\npset.addPrimitive(protectedDiv, 2)\npset.addTerminal(1.0, name=\"1.0\")\npset.addTerminal(2.0, name=\"2.0\")\npset.addTerminal(0.5, name=\"0.5\")\npset.addTerminal(10.0, name=\"10.0\")\n# También podemos añadir constantes efímeras\npset.addEphemeralConstant(\"rand101\", lambda: random.uniform(-5, 5))\n\n# Fitness para minimizar el error\ncreator.create(\"FitnessMin\", base.Fitness, weights=(-1.0,))\ncreator.create(\"Individual\", gp.PrimitiveTree, fitness=creator.FitnessMin)"),
    ("code", "toolbox = base.Toolbox()\ntoolbox.register(\"expr\", gp.genHalfAndHalf, pset=pset, min_=1, max_=3)\ntoolbox.register(\"individual\", tools.initIterate, creator.Individual, toolbox.expr)\ntoolbox.register(\"population\", tools.initRepeat, list, toolbox.individual)\ntoolbox.register(\"compile\", gp.compile, pset=pset)\n\ndef evalSymbReg(individual):\n    # Compilar el individuo en una función ejecutable\n    func = toolbox.compile(expr=individual)\n    sqerrors = []\n    for v, p, i, real_e in dataset:\n        try:\n            pred_e = func(v, p, i)\n        except:\n            pred_e = float('inf')\n        sqerrors.append((pred_e - real_e)**2)\n    # Retornar el error cuadrático medio\n    return math.fsum(sqerrors) / len(dataset),\n\ntoolbox.register(\"evaluate\", evalSymbReg)\ntoolbox.register(\"select\", tools.selTournament, tournsize=5)\ntoolbox.register(\"mate\", gp.cxOnePoint)\ntoolbox.register(\"expr_mut\", gp.genFull, min_=0, max_=2)\ntoolbox.register(\"mutate\", gp.mutUniform, expr=toolbox.expr_mut, pset=pset)"),
    ("markdown", "## 3. Evolución"),
    ("code", "from deap import algorithms\n\npop = toolbox.population(n=300)\nhof = tools.HallOfFame(1)\nstats = tools.Statistics(lambda ind: ind.fitness.values)\nstats.register(\"avg\", np.mean)\nstats.register(\"std\", np.std)\nstats.register(\"min\", np.min)\nstats.register(\"max\", np.max)\n\nprint(\"Iniciando evolución...\")\npop, logbook = algorithms.eaSimple(pop, toolbox, 0.7, 0.1, 50, stats=stats, halloffame=hof, verbose=True)\nprint(\"¡Evolución terminada!\")"),
    ("markdown", "## 4. Resultados y Visualización\nMostramos el mejor modelo matemático encontrado y comparamos sus predicciones con los datos reales."),
    ("code", "best_model = hof[0]\nprint(\"Mejor fórmula encontrada:\\n\", best_model)\n\nfunc = toolbox.compile(expr=best_model)\npredicciones = [func(v, p, i) for v, p, i, _ in dataset]\nreales = [e for _, _, _, e in dataset]\n\nplt.figure(figsize=(8,5))\nplt.scatter(reales, predicciones, color='red', alpha=0.6, label='Predicción vs Real')\nplt.plot([min(reales), max(reales)], [min(reales), max(reales)], color='blue', linestyle='--', label='Ajuste Perfecto')\nplt.xlabel('Consumo Energético Real')\nplt.ylabel('Consumo Predicho por PG')\nplt.title('Regresión Simbólica: Predicción de Energía de Mini-Robot')\nplt.legend()\nplt.grid(True)\nplt.show()")
]

create_notebook("Notebook_Punto2_Galletas.ipynb", nb1_cells)
create_notebook("Notebook_Punto4_Inventado.ipynb", nb2_cells)
print("Notebooks created successfully!")
